package sigil

import (
	"encoding/json"
	"math"
	"os"
	"reflect"
	"strings"
	"testing"
)

type row struct {
	TierIndex   int       `json:"tierIndex"`
	WallClockMs float64   `json:"wallClockMs"`
	Raw         Telemetry `json:"raw"`
	TimestampMs int64     `json:"timestampMs"`
	AmountCents int       `json:"amountCents"`
	Clamped     Telemetry `json:"clamped"`
	Violations  []string  `json:"violations"`
	Hash        uint32    `json:"hash"`
	RarityScore float64   `json:"rarityScore"`
	Rarity      Rarity    `json:"rarity"`
}

// corpus is the whole file. sigilDigest is deliberately absent: geometry is
// TypeScript-only — the server stores a seed and a rarity, it does not render —
// so Go has nothing to check it against and its decoder ignores the column.
type corpus struct {
	Version int               `json:"version"`
	Engine  string            `json:"engine"`
	Probe   map[string]string `json:"probe"`
	Rows    []row             `json:"rows"`
}

func readCorpus(t *testing.T) corpus {
	t.Helper()
	b, err := os.ReadFile("testdata/corpus.json")
	if err != nil {
		t.Fatal(err)
	}
	var c corpus
	if err := json.Unmarshal(b, &c); err != nil {
		t.Fatal(err)
	}
	return c
}

func load(t *testing.T) []row {
	t.Helper()
	c := readCorpus(t)
	if c.Engine == "" {
		t.Fatal("corpus has no engine field; regenerate with `npm run gencorpus`")
	}
	return c.Rows
}

// The corpus records which JavaScript engine produced it. Math.sin/cos/pow are
// implementation-dependent per ECMAScript and feed generateSigil, so a corpus
// regenerated on a different engine is a different contract even when the diff
// looks empty.
//
// IMPORTANT: bump this deliberately, never to make a test pass. The probes are
// the only signal that transcendental math moved underneath you, and the failure
// looks identical whether the cause is a deliberate engine switch or an engine
// that changed its sin implementation in a patch release.
//
// Measured: Node 22 (V8 12.4) and Bun 1.3.14 (JavaScriptCore) currently agree on
// all three probes, so the engine string — not the probes — is what catches a
// switch between those two.
const pinnedEngine = "node-v8"

func TestCorpusEngineIsPinned(t *testing.T) {
	c := readCorpus(t)

	if !strings.HasPrefix(c.Engine, pinnedEngine+"/") {
		t.Fatalf("corpus generated by %q, expected %s/*. See app/sigil/ENGINE-PINNING.md", c.Engine, pinnedEngine)
	}

	want := map[string]string{
		"cos07":   "0.7648421872844885",
		"sin23":   "0.7457052121767203",
		"pow11_3": "1.3310000000000004",
	}
	for k, v := range want {
		if c.Probe[k] != v {
			t.Fatalf("transcendental probe %s drifted: got %q want %q (engine %s). See app/sigil/ENGINE-PINNING.md", k, c.Probe[k], v, c.Engine)
		}
	}
}

func sorted(s []string) []string {
	// Always non-nil: append([]string(nil)) with zero elements returns nil,
	// which makes reflect.DeepEqual distinguish [] from nil. Both mean
	// "no violations" here.
	out := make([]string, len(s))
	copy(out, s)
	for i := range out {
		for j := i + 1; j < len(out); j++ {
			if out[j] < out[i] {
				out[i], out[j] = out[j], out[i]
			}
		}
	}
	return out
}

func TestClampMatchesTypeScript(t *testing.T) {
	for i, r := range load(t) {
		got := ClampTelemetry(r.Raw, r.TierIndex, r.WallClockMs)
		if got.Telemetry != r.Clamped {
			t.Fatalf("row %d clamp mismatch\n go: %+v\n ts: %+v", i, got.Telemetry, r.Clamped)
		}
		if !reflect.DeepEqual(sorted(got.Violations), sorted(r.Violations)) {
			t.Fatalf("row %d violations mismatch\n go: %v\n ts: %v", i, sorted(got.Violations), sorted(r.Violations))
		}
	}
}

func TestHashMatchesTypeScript(t *testing.T) {
	for i, r := range load(t) {
		got := HashSeed(BurnSeed{
			TierIndex: r.TierIndex, AmountCents: r.AmountCents,
			TimestampMs: r.TimestampMs, Telemetry: r.Clamped,
		})
		if got != r.Hash {
			t.Fatalf("row %d hash mismatch: go=%d ts=%d (ts=%d)", i, got, r.Hash, r.TimestampMs)
		}
	}
}

// The client labels the preview with a rarity and the server mints one. A
// disagreement is silent in exactly the way a hash mismatch is: the user is told
// they earned one classification and the ledger records another.
func TestRarityMatchesTypeScript(t *testing.T) {
	for i, r := range load(t) {
		if got := RarityScore(r.Clamped, r.TierIndex); got != r.RarityScore {
			t.Fatalf("row %d score mismatch: go=%v ts=%v", i, got, r.RarityScore)
		}
		if got := Classify(r.Clamped, r.TierIndex); got != r.Rarity {
			t.Fatalf("row %d rarity mismatch: go=%q ts=%q", i, got, r.Rarity)
		}
	}
}

// The scoring is integer arithmetic specifically so a threshold comparison can
// never straddle a last-ulp difference between the two languages. If a score
// ever comes back fractional, that guarantee is gone.
func TestRarityScoreIsIntegral(t *testing.T) {
	for i, r := range load(t) {
		got := RarityScore(r.Clamped, r.TierIndex)
		if got != math.Trunc(got) {
			t.Fatalf("row %d score is not an integer: %v", i, got)
		}
		if got < 0 || got > 1000 {
			t.Fatalf("row %d score %v outside 0-1000", i, got)
		}
	}
}

// Out-of-range tiers must not panic — tierIndex reaches this from a request body.
func TestClassifyHandlesOutOfRangeTier(t *testing.T) {
	tel := Telemetry{DropletsLanded: 80, PeakVelocity: 1200, TiltEnergy: 12, HoldMs: 4000}
	for _, tier := range []int{-5, -1, 6, 99} {
		if got := Classify(tel, tier); got == "" {
			t.Fatalf("tier %d returned empty rarity", tier)
		}
	}
	// Clamping, not wrapping: a tier below the floor scores as tier 0.
	if Classify(tel, -1) != Classify(tel, 0) {
		t.Fatal("negative tier should clamp to tier 0")
	}
	if Classify(tel, 99) != Classify(tel, 5) {
		t.Fatal("oversized tier should clamp to the top tier")
	}
}

// Go's float->int conversion is implementation-specific for NaN/Inf; JS
// ToUint32 yields 0. Hashing must never be platform-dependent.
func TestToUint32HandlesNonFinite(t *testing.T) {
	for _, v := range []float64{math.NaN(), math.Inf(1), math.Inf(-1)} {
		if got := toUint32(v); got != 0 {
			t.Fatalf("toUint32(%v) = %d, want 0", v, got)
		}
	}
}

// A caller that skips ClampTelemetry must still get a stable hash.
func TestHashStableWithNonFiniteTelemetry(t *testing.T) {
	s := BurnSeed{TierIndex: 2, AmountCents: 999, TimestampMs: 1750000000000,
		Telemetry: Telemetry{math.NaN(), math.Inf(1), math.NaN(), 5000}}
	if HashSeed(s) != HashSeed(s) {
		t.Fatal("hash unstable for non-finite telemetry")
	}
}
