// Package sigil is the server-authoritative half of the sigil pipeline.
//
// It is a deliberate duplicate of app/sigil/sigil.ts (hashSeed) and
// app/sigil/telemetry.ts (clampTelemetry). Do not "improve" either side
// independently — testdata/corpus.json is generated by TypeScript and verified
// here, and it is the only thing that catches drift between the two.
//
// A mismatch does not crash. It mints a sigil that differs from the one the
// user watched form on their screen.
package sigil

import "math"

// ---------------------------------------------------------------------------
// Telemetry
// ---------------------------------------------------------------------------

type Telemetry struct {
	DropletsLanded float64 `json:"dropletsLanded"`
	PeakVelocity   float64 `json:"peakVelocity"`
	TiltEnergy     float64 `json:"tiltEnergy"`
	HoldMs         float64 `json:"holdMs"`
}

const (
	simGravity        = 1400.0
	simSpawnVyMax     = 120.0
	simSpawnVxMax     = 45.0
	simMaxPourMs      = 15000.0
	simMaxTiltRate    = 6.0
	simDropletTolerar = 1.15
)

var tierFlow = [6]float64{10, 16, 20, 24, 28, 34}

type ClampResult struct {
	Telemetry  Telemetry
	Violations []string
}

// ClampTelemetry bounds what a client may claim about a pour.
//
// IMPORTANT: the arithmetic must match telemetry.ts operation for operation.
// Notably maxSpeed uses an explicit sqrt rather than math.Hypot — Hypot and
// JS Math.hypot may differ in the last ulp, and this value feeds HashSeed.
func ClampTelemetry(raw Telemetry, tierIndex int, wallClockMs float64) ClampResult {
	flow := tierFlow[0]
	if tierIndex >= 0 && tierIndex < len(tierFlow) {
		flow = tierFlow[tierIndex]
	}

	var violations []string
	take := func(key string, value, max float64) float64 {
		safe := value
		if math.IsNaN(safe) || math.IsInf(safe, 0) {
			safe = 0
		}
		if safe < 0 {
			safe = 0
		}
		if safe > max {
			violations = append(violations, key)
		}
		return math.Min(safe, max)
	}

	holdMs := take("holdMs", raw.HoldMs, math.Min(wallClockMs, simMaxPourMs))
	holdS := holdMs / 1000

	maxDroplets := math.Ceil(flow * holdS * simDropletTolerar)
	dropletsLanded := take("dropletsLanded", raw.DropletsLanded, maxDroplets)

	maxFall := simSpawnVyMax + simGravity*math.Min(holdS, 1.2)
	maxSpeed := math.Sqrt(maxFall*maxFall+simSpawnVxMax*simSpawnVxMax) * 1.1
	peakVelocity := take("peakVelocity", raw.PeakVelocity, maxSpeed)

	tiltEnergy := take("tiltEnergy", raw.TiltEnergy, simMaxTiltRate*holdS)

	return ClampResult{
		Telemetry: Telemetry{
			DropletsLanded: dropletsLanded,
			PeakVelocity:   peakVelocity,
			TiltEnergy:     tiltEnergy,
			HoldMs:         holdMs,
		},
		Violations: violations,
	}
}

// ---------------------------------------------------------------------------
// Seed hashing
// ---------------------------------------------------------------------------

type BurnSeed struct {
	TierIndex   int
	AmountCents int
	TimestampMs int64
	Telemetry   Telemetry
}

// toUint32 replicates the ECMAScript ToUint32 abstract operation.
//
// Note: the high bits of TimestampMs do NOT need masking for correctness — the
// hash loop below reads only bytes 0-3, which is already the low 32 bits. A
// naive int64 port produces the same value; this was verified, not assumed.
//
// IMPORTANT: what this DOES guard is NaN and Inf. Converting either to an
// integer type in Go is implementation-specific behavior per the spec, while
// JS ToUint32 yields 0. ClampTelemetry should zero these before they arrive,
// so reaching this path means a caller bypassed the clamp — fail closed rather
// than emit a platform-dependent hash.
func toUint32(v float64) uint32 {
	if math.IsNaN(v) || math.IsInf(v, 0) {
		return 0
	}
	t := math.Trunc(v)
	m := math.Mod(t, 4294967296)
	if m < 0 {
		m += 4294967296
	}
	return uint32(m)
}

// HashSeed mirrors hashSeed() in sigil.ts: FNV-1a over a fixed field order.
// Never iterate a map here — key order is undefined and would drift per run.
func HashSeed(s BurnSeed) uint32 {
	parts := []uint32{
		toUint32(float64(s.TierIndex)),
		toUint32(float64(s.AmountCents)),
		toUint32(float64(s.TimestampMs)),
		toUint32(s.Telemetry.DropletsLanded),
		toUint32(jsRound(s.Telemetry.PeakVelocity)),
		toUint32(jsRound(s.Telemetry.TiltEnergy * 1000)),
		toUint32(s.Telemetry.HoldMs),
	}

	h := uint32(0x811c9dc5)
	for _, p := range parts {
		for b := 0; b < 4; b++ {
			h ^= (p >> (b * 8)) & 0xff
			h *= 0x01000193 // uint32 wraparound == Math.imul
		}
	}
	return h
}

// jsRound matches Math.round, which rounds half UP (toward +Inf), not
// half-to-even like Go's math.Round does for .5 on negatives.
// Values here are non-negative, but the difference is documented so a future
// signed field does not silently diverge.
func jsRound(v float64) float64 {
	return math.Floor(v + 0.5)
}
